### ISSUE TITLE
Plugin error message with latest AdiIRC 3.8 beta build 2020/2/17

### ISSUE THREAD

**Issue by darkred** [Xesyto/AdiIRC-Join-Part-Filter#1]
Greetings

Using latest version 4 of the plugin.

With today's beta version of AdiIRC, 3.8 build 2020/2/17,
whenever closing a server via rightlicking in the treebar (or just while being idle to a channel)
I'm getting the following error: 
(no matter how many times I click OK, the error window keeps on displaying)

```
Plugin Join-Part Filter.dll caused an error 

 System.NullReferenceException: Object reference not set to an instance of an object.
   at JoinPartFilter.Filter.OnChannelNormalMessage(ChannelNormalMessageArgs argument)
```

![2020-02-17_210238](https://user-images.githubusercontent.com/723651/74680445-4ec48600-51c9-11ea-94b1-72977426e269.jpg)

A similar error is displayed when I connect to a channel:

```
Plugin Join-Part Filter.dll caused an error 

 System.NullReferenceException: Object reference not set to an instance of an object.
   at JoinPartFilter.Filter.OnChannelJoin(ChannelJoinArgs argument)
```

P.S. Thank you for this very useful plugin

**Comment by darkred** [comment]
The issue was caused by a bug in that AdiIRC beta build. Fixed in new beta 2020/2/23:
| *Fixed closing a server window sometimes doesn't close the channel windows.*
